{% set version = '1.0-1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-roi.plugin.quadprog
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ROI.plugin.quadprog_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ROI.plugin.quadprog/ROI.plugin.quadprog_{{ version }}.tar.gz
  sha256: e891778a451cb8688fcb885e02d4ac51c09c83f8fb5344a4c271cad469712087

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-roi >=0.3_0
    - r-quadprog
    - r-slam
  run:
    - r-base
    - r-roi >=0.3_0
    - r-quadprog
    - r-slam

test:
  commands:
    - $R -e "library('ROI.plugin.quadprog')"           # [not win]
    - "\"%R%\" -e \"library('ROI.plugin.quadprog')\""  # [win]

about:
  home: http://roi.r-forge.r-project.org/, https://r-forge.r-project.org/projects/roi/
  license: GPL-3.0-only
  summary: Enhances the R Optimization Infrastructure ('ROI') package by registering the 'quadprog'
    solver. It allows for solving quadratic programming (QP) problems.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - janjagusch


# Package: ROI.plugin.quadprog
# Version: 1.0-1
# Title: 'quadprog' Plug-in for the 'R' Optimization Infrastructure
# Authors@R: c(person("Stefan", "Theussl", role = c("aut", "cre"), email = "Stefan.Theussl@R-Project.org", comment = c(ORCID = "0000-0002-6523-4620")))
# Description: Enhances the R Optimization Infrastructure ('ROI') package by registering the 'quadprog' solver. It allows for solving quadratic programming (QP) problems.
# Imports: methods, quadprog, ROI (>= 0.3-0), slam
# License: GPL-3
# URL: http://roi.r-forge.r-project.org/, https://r-forge.r-project.org/projects/roi/
# NeedsCompilation: no
# Packaged: 2023-07-07 17:48:26 UTC; theussl
# Author: Stefan Theussl [aut, cre] (<https://orcid.org/0000-0002-6523-4620>)
# Maintainer: Stefan Theussl <Stefan.Theussl@R-Project.org>
# Repository: CRAN
# Date/Publication: 2023-07-12 22:40:06 UTC
